APP_VERSION_CODE=1000003
APP_VERSION_NAME=1.2
APP_PACKAGE=org.telegram.messenger
IS_PRIVATE=false
org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=768M -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configureondemand=false
org.gradle.caching=true
org.gradle.workers.max=2
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.enableR8.fullMode=true
kotlin.incremental=true
kotlin.incremental.usePreciseJavaTracking=true
kotlin.daemon.jvmargs=-Xmx768M
